---
- name: include host details file
  include_vars: ipam.yml

- set_fact:
    hostname: "{% for host in host_ips %}{% if inventory_hostname == host['name'] %}{{ host['name'] }}{% endif %}{% endfor %}"

- debug:
    var: hostname

- name: set HostName
  shell: /usr/bin/hostnamectl set-hostname {{hostname}}




