- name: find the primary interface
  shell: ls /etc/sysconfig/network-scripts/|grep ^ifcfg|head -1
  register: interface

- name: Template the ifcfg file
  template:
    src: ifcfg_ens160.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ens160
    mode: 0644
    owner: root
    group: root
  notify: 'Reload Network'




