- name: find the primary interface
  shell: ls /etc/sysconfig/network-scripts/|grep ^ifcfg|head -1
  register: interface

- name: Temlate the ifcfg file
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/
    mode: 0644
    owner: root
    group: root




