- name: Copy rhel8 iso
  copy:
    src: /home/antogx/rhel-8.4-x86_64-dvd.iso
    dest: /home/antogx/rhel-8.4-x86_64-dvd.iso

- name: Mount the iso
  mount:
    path: /media/rhel8-server
    src: /home/antogx/rhel-8.4-x86_64-dvd.iso 
    fstype: auto
    opts: loop
    state: mounted

- copy: 
    src: "{{ item }}"
    dest: "{{ item }}"
  register: dest_rhel8_repo_result
  loop:
    - /etc/yum.repos.d/rhel8-server-BaseOS.repo
    - /etc/yum.repos.d/rhel8-server-AppStream.repo

- name: Install EPEL Repo
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: installed
    validate_certs: false
    disable_gpg_check: true
  changed_when: true
  notify: Yum Clean
   
    
  


  
    

  