- hosts: all
  become: yes
  gather_facts: false
  vars:
  tasks:
  - debug:
      msg: "Test"

  - name: Update sudoers
    sudoers:
      name: antogx_sudo_access
      state: present
      user: antogx
      runas: root
      commands: ALL
      nopassword: yes

