- hosts: localhost
  become: yes
  gather_facts: false
  vars:
    - fullname: '/first/second'
  tasks:
  - mymodule:
      firstname: roms
      lastname: davids
    register: name1

  - debug: 
      var: name1
