- hosts: worker1
  become: yes
  gather_facts: false
  vars:
    - fullname: '/first/second'
  tasks:
  - name: Check running kubernetes or docker processes
    shell: ps aux|egrep -i 'kube'|grep -v grep
    register: kube_process

  - debug:
      msg: "{{ item.split()[1] }}"
    loop: "{{ kube_process.stdout_lines }}"

  - name: Kill kubernetes or docker processes
    shell: kill -9 {{ item.split()[1] }}
    loop: "{{ kube_process.stdout_lines }}"
    ignore_errors: yes
