- hosts: central:central_db
  become: yes
  gather_facts: no
  vars: 
    centreon_version: '21.04'
    php_version: "{{ '7.3' if centreon_version == '21.04' else 
                  'remi-8.0' if centreon_version == '21.10' }}" ## Refer documentation for future releases
    cert_name: "{{ 'centreon-dev.unix.srv.westpac.com.au.pem' if 'dlw210729164826' in inventory_hostname else
                'dlw210729164918.obm.nix.srv.westpac.com.au.pem' if 'dlw210729164918' in inventory_hostname else
                'pli211119171317.obm.nix.srv.westpac.com.au.pem' if 'pli211119171317' in inventory_hostname }}"
  
  tasks:

  - name: Enable Centreon repo
    include_tasks: centreon_repo_task.yml

  - name: yum clean all
    command: yum clean all
    args:
      warn: no

  - name: Centreon packages installation 
    block:       

    - name: list enabled php module
      command: dnf module list php -y
      register: dnf_module
      args:
        warn: no

    - name: dnf module reset php -y
      command: dnf module reset php -y
      args:
        warn: no
      when: php_version + ' [e]' not in dnf_module.stdout

    - name: Enable PHP {{php_version}}
      command: dnf module enable php:{{php_version}} -y
      args:
        warn: no

    - name: list enabled module
      command: dnf module list php
      register: dnf_module
      args:
        warn: no

    - debug:
        var: dnf_module.stdout_lines

    - fail:
        msg: "PHP {{php_version}} is not activated"
      when: php_version + ' [e]' not in dnf_module.stdout

    - name: Install centreon packages
      dnf:
        name: 
          - centreon-base-config-centreon-engine 
          - centreon-widget*
          - mod_ssl 
          - mod_security 
          - openssl
        state: installed
        enablerepo: "Westpac_EPEL_epel_rhel8_x86-64, codeready-builder-for-rhel-8-x86_64-rpms, 
          rhel-8-for-x86_64-appstream-rpms, rhel-8-for-x86_64-baseos-rpms, rhel8_centreon_stable, rhel8_centreon_stable_noarch"

    - name: Update /etc/httpd/conf.d/10-centreon.conf for Centreon {{ centreon_version }}
      template: 
        src: 10-centreon.conf_{{centreon_version}}.j2
        dest: /etc/httpd/conf.d/10-centreon.conf
        mode: 0644
        owner: root
        group: root
        backup: yes

    - name: Set the PHP time zone
      lineinfile:
        path: /etc/php.d/50-centreon.ini
        line: "date.timezone = Australia/Sydney"

    - name: User and groups setup
      include_tasks: users_and_groups.yml

    - name: Copy the custom nrpe scripts to Server
      copy:
        src: nrpe_scripts/check_centreon_master
        dest: /usr/lib64/nagios/plugins/
        owner: root
        group: root
        mode: 0755

    - name: Copy the nrpe cfg file
      copy:
        src: nrpe_cfg/check_centreon_master.cfg
        dest: /etc/nrpe.d/
        owner: root
        group: root
        mode: 0755
      register: cfg_task

    - name: Restart nrpe if cfg was changed
      systemd:
        name: nrpe
        state: restarted
      when: cfg_task.changed

  ## Services
    - name: Enable the services
      systemd:
        name: "{{ item }}"
        enabled: yes
      loop: [php-fpm, httpd, centreon, cbd, centengine, gorgoned]

    - name: start httpd and php
      service:
        name: "{{item}}"
        state: restarted
      loop: 
        - php-fpm
        - httpd
    when: "'central' in  group_names" 

## DB installation
  - name: DB installation on db servers
    block:

    - name: User and groups setup
      include_tasks: users_and_groups.yml

    - name: Install centreon-database on dedicated DB servers
      dnf:
        name: centreon-database
        state: installed
        enablerepo: "Westpac_EPEL_epel_rhel8_x86-64, codeready-builder-for-rhel-8-x86_64-rpms, 
          rhel-8-for-x86_64-appstream-rpms, rhel-8-for-x86_64-baseos-rpms, rhel8_centreon_stable, rhel8_centreon_stable_noarch"

    - name: deamon-reload
      systemd:
        daemon_reload: yes

    - name: Remove /var/lib/mysql/.bash_profile
      command: rm -rf /var/lib/mysql/.bash_profile
      args:
        warn: no

    - name: restart mariadb
      service: 
        name: mariadb
        state: restarted
        enabled: yes

    - name: Creating .bash_profile if its not exist
      copy:
        src: /etc/skel/.bash_profile
        dest: /var/lib/mysql/.bash_profile
        remote_src: yes
        force: no
        owner: mysql
        group: mysql

    - name: set umask
      lineinfile:
        path: /var/lib/mysql/.bash_profile
        line: umask 0002

    - name: Copy the custom nrpe scripts to Server
      copy:
        src: nrpe_scripts/check_centreon_database
        dest: /usr/lib64/nagios/plugins/
        owner: root
        group: root
        mode: 0755

    - name: Copy the nrpe cfg file
      copy:
        src: nrpe_cfg/check_centreon_database.cfg
        dest: /etc/nrpe.d/
        owner: root
        group: root
        mode: 0755
      register: cfg_task

    - name: Restart nrpe if cfg was changed
      systemd:
        name: nrpe
        state: restarted
      when: cfg_task.changed
    
    when: "'central_db' in  group_names" 
    
