- hosts: worker1
  become: yes
  become_method: sudo
  gather_facts: yes
  collections:
    - community.general
  tasks:  
  - debug:
      msg: "Test"
  - include_role:
      name: rhel8_soe


###ftp yum repo