- hosts: servers1
  gather_facts: yes
  become: yes
  tasks:
  - block:
      - set_fact:
          pkg: "{{ 'sudo-1.8.23-10.el7_9.1.x86_64.rpm' if ansible_distribution_version == '7.9' else (
            'sudo-1.8.23-4.el7_7.3.x86_64.rpm' if ansible_distribution_version == '7.7' else (
            'sudo-1.8.23-3.el7_6.2.x86_64.rpm' if ansible_distribution_version == '7.6' else (
            'sudo-1.8.6p3-29.el6_10.4.x86_64.rpm' if ansible_distribution_version == '6.10' else (
            'sudo-1.8.29-5.el8_2.1.x86_64.rpm' if ansible_distribution_version == '8.2' else (
            'sudo-1.8.29-6.el8_3.1.x86_64.rpm' if ansible_distribution_version == '8.3'))))) }}"

      - name: Fail if the host not able to set the corresponding package
        fail:
          msg: "Not able to set the required package"
        when: pkg|length < 5

      - name: Copy rpm to the destination host
        copy:
          src: '/home/l122887/CVE_2021_3156/{{pkg|trim}}'
          dest: /tmp/CVE_2021_3156/
          mode: 755

      # - raw: echo -e "$(cat /etc/redhat-release|cut -d " " -f7) $(ls /tmp/CVE_2021_3156/|cut -d "." -f4)"
      #   register: lst

      # - debug: 
      #     var: lst.stdout

      - yum:
          name: '/tmp/CVE_2021_3156/{{pkg|trim}}'
          state: latest


      - name: PIV
        shell: |
          cat /etc/redhat-release
          rpm -q sudo 
          sudo -u l122887 date 
        register: piv

      - name: PIV_out
        debug:
          msg: "{{ piv.stdout_lines }}"

    when: "'7.9' in ansible_distribution_version or 
          '7.7' in ansible_distribution_version or 
          '7.6' in ansible_distribution_version or 
          '6.10' in ansible_distribution_version or
          '8.2' in ansible_distribution_version or 
          '8.3' in ansible_distribution_version"
  
