- name: Update /etc/hosts on all hosts
  copy:
    content: |
        127.0.0.1       localhost.localdomain   localhost       localhost4      localhost4.localdomain4
        {% for host in host_ips %}
        {{ host['ip1'] }} {{ host['name'] }}
        {% endfor %}
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  ignore_errors: true
