
# - include_tasks: sudo.yml

# - include_tasks: timezone.yml

# - include_tasks: firewalld.yml

# - include_tasks: selinux.yml

# - include_tasks: runlevel.yml

# # - include_tasks: repos.yml
# #   when: inventory_hostname not in groups['control']

- include_tasks: hostname.yml

- include_tasks: network_rhel8.yml
  when: ansible_distribution_major_version == '8'

- include_tasks: network_rhel9.yml
  when: ansible_distribution_major_version == '9'

# - include_tasks: hostsfile.yml

# - include_tasks: rh_register.yml
#   when: not inventory_hostname.startswith('master')

# - include_tasks: full_patching.yml
#   when: 
#     - rh_register is changed
#     - not inventory_hostname.startswith('master')

# - include_tasks: reboot.yml
#   when: not inventory_hostname.startswith('master')



