- name: find the primary interface
  shell: ls /etc/NetworkManager/system-connections|head -1|cut -d "." -f1
  register: interface

- name: Configure ip4 address
  community.general.nmcli:
    conn_name: "{{ interface.stdout }}"
    ifname: "{{ interface.stdout }}"
    type: ethernet
    ip4: "{% for host in host_ips %}{% if inventory_hostname == host['name'] %}{{ host['ip1'] }}{% endif %}{% endfor %}"
    state: present
    method4: manual
  notify: 'Reload Network'