---
- name: Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Service Inactive"
      action:
        run_job_template:
          name: EDA1 Template
          organization: Default
        # run_playbook:
        #   name: action.yml

### ansible-rulebook --rulebook webhook.yml -i inventory.yml -v