- name: yum clean
  shell: |
    yum clean all 
    dnf clean all

- name: check containerd is installed
  shell: rpm -q containerd.io
  register: containerd_rpm_stat
  ignore_errors: true

- name: Install containerd.io
  dnf: 
    name: 'https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.6.6-3.1.el8.x86_64.rpm'
    state: installed
    disable_gpg_check: true
  when: containerd_rpm_stat is failed

- name: check docker is installed
  shell: rpm -q docker-ce
  register: docker_rpm_stat
  ignore_errors: true

- name: Configure docker repo
  shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: false

- name: Install docker-ce 
  dnf:
    name: docker-ce
    state: latest 
    disable_gpg_check: true
  when: docker_rpm_stat is failed

- name: Start and enable docker
  systemd: 
    name: docker
    state: started
    enabled: true
  register: docker_start 
  ignore_errors: true

- name: Reboot if the docker start fails
  block:
  - name: Reboot
    reboot:
      msg: "Reboot"
      reboot_timeout: 180
      post_reboot_delay: 10

  - name: Start and enable docker
    systemd: 
      name: docker
      state: started
      enabled: true
    register: docker_start 
  when: docker_start is failed
      

  