- name: Comment out the line
  hosts: servers1
  gather_facts: yes
  become: yes
  tasks:

  - shell: cat /etc/crypto-policies/policies/modules/WBC.pmod |grep 'sign = -RSA-PSS-SHA1 -RSA-SHA1 -ECDSA-SHA1'
    register: out1

  - debug: 
      var: out1.stdout_lines

  - name: Comment out the line
    replace:
      path: /etc/crypto-policies/policies/modules/WBC.pmod
      regexp: '^(sign = [A-Za-z0-1 -\\\/]+)'
      replace: '#\1'

  - shell: update-crypto-policies --set DEFAULT:WBC