- hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: Show the IPs utilised
    debug:
      msg: "{{inventory_hostname}} Primary: {{ansible_facts.ens160.ipv4.address if ansible_facts.ens160.ipv4.address is defined else ''}}  
                                   Secondary: {{ansible_facts.ens224.ipv4.address if ansible_facts.ens224.ipv4.address is defined else ''}}" 
    




  # - name: Update ipam.txt with all IPs
  #   lineinfile:
  #     path: ~/ansible/roles/rhel8_soe/files/ipam.txt
  #     line: "{{ item }}"
  #     # regexp: "*{{inventory_hostname}}*"
  #   become: false
  #   delegate_to: localhost
  #   loop:
  #   - "{{ansible_facts.ens160.ipv4.address}}"
  #   - "{{ansible_facts.ens224.ipv4.address}}"

  # - shell: cat ~/ansible/roles/rhel8_soe/files/ipam.txt
  #   register: ipam
  #   become: no
  #   delegate_to: localhost
  #   run_once: true

  # - set_fact:
  #     latest_ip: "{{ ipam.stdout_lines|sort(reverse=true)|first }}"

  # - set_fact:  
  #     next_ip: "{{ latest_ip.split('.')[0:3]|join('.') }}.{{latest_ip.split('.')[3]|int + 1 }}"




